"""Subprocess smoke tests for ``python -m velotype`` batch commands (real entrypoint)."""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

from pythonpath_helpers import repo_pythonpath

_REPO_ROOT = Path(__file__).resolve().parent.parent


def _env() -> dict[str, str]:
    return {**os.environ, "PYTHONPATH": repo_pythonpath(_REPO_ROOT)}


def test_subprocess_batch_stub_writes_pyi_files(tmp_path: Path) -> None:
    r = subprocess.run(
        [
            sys.executable,
            "-m",
            "velotype",
            "batch",
            "stub",
            "fixtures.batch_pkg",
            "--out-dir",
            str(tmp_path),
        ],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
        env=_env(),
    )
    assert r.returncode == 0, r.stderr + r.stdout
    pyi = list(tmp_path.glob("*.pyi"))
    assert len(pyi) == 2
    assert "Wrote" in r.stdout
    joined = "\n".join(p.read_text() for p in pyi)
    assert "RootModel" in joined and "SubModel" in joined


def test_subprocess_batch_stub_merge_merged_pyi(tmp_path: Path) -> None:
    r = subprocess.run(
        [
            sys.executable,
            "-m",
            "velotype",
            "batch",
            "stub",
            "fixtures.batch_pkg",
            "--out-dir",
            str(tmp_path),
            "--merge",
        ],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
        env=_env(),
    )
    assert r.returncode == 0, r.stderr
    merged = tmp_path / "merged.pyi"
    assert merged.is_file()
    text = merged.read_text()
    assert "RootModel" in text and "SubModel" in text
    assert "Merged stubs generated by velotype batch" in text


def test_subprocess_batch_ir_merged_json_one_model_with_exclude(
    tmp_path: Path,
) -> None:
    r = subprocess.run(
        [
            sys.executable,
            "-m",
            "velotype",
            "batch",
            "ir",
            "fixtures.batch_pkg",
            "--out-dir",
            str(tmp_path),
            "--merge",
            "--exclude",
            "*/models.py",
        ],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
        env=_env(),
    )
    assert r.returncode == 0, r.stderr
    data = json.loads((tmp_path / "merged.json").read_text())
    assert isinstance(data, list)
    assert len(data) == 1
    assert data[0].get("name") == "RootModel"


def test_subprocess_batch_ir_json_files_match_discovery(tmp_path: Path) -> None:
    r = subprocess.run(
        [
            sys.executable,
            "-m",
            "velotype",
            "batch",
            "ir",
            "fixtures.batch_pkg",
            "--out-dir",
            str(tmp_path),
        ],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
        env=_env(),
    )
    assert r.returncode == 0
    json_files = list(tmp_path.glob("*.json"))
    assert len(json_files) == 2
    names = set()
    for f in json_files:
        names.add(json.loads(f.read_text())["name"])
    assert names == {"RootModel", "SubModel"}


def test_subprocess_batch_stub_unknown_package_exits_2(tmp_path: Path) -> None:
    r = subprocess.run(
        [
            sys.executable,
            "-m",
            "velotype",
            "batch",
            "stub",
            "totally_unknown_pkg_zz",
            "--out-dir",
            str(tmp_path),
        ],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
        env=_env(),
    )
    assert r.returncode == 2


def test_subprocess_velotype_help_includes_batch() -> None:
    r = subprocess.run(
        [sys.executable, "-m", "velotype", "--help"],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
        env=_env(),
    )
    assert r.returncode == 0
    out = r.stdout + (r.stderr or "")
    assert "batch" in out.lower()
