"""Stub generated by velotype — ModelSpec IR."""

from __future__ import annotations

import typing
from dataclasses import dataclass

@dataclass(frozen=True)
class Mixed:
    cb: typing.Callable[[int], bool]
    choice: str | None
    tag: typing.Literal['a'] = 'a'

