"""Stub generated by velotype — ModelSpec IR."""

from __future__ import annotations

import datetime
import typing
from dataclasses import dataclass

@dataclass
class WithDt:
    created: datetime.datetime
    nested: list[datetime.date]

